image: node:8.11.1

pages:
 cache:
  paths:
  - node_modules/

 stage: deploy
 script:
 - yarn install
 - yarn global add forever
 - yarn build
 - rm -rf public
 - mv build public
 - yarn start-live
 artifacts:
  paths:
  - public
 only:
 - master
