image: node:8.11.1

pages:
 cache:
  paths:
  - node_modules/

 before_script:
 - docker info
 - yarn global add forever

 stage: deploy
 script:
 - yarn install
 - yarn build
 - rm -rf public
 - mv build public
 artifacts:
  paths:
  - public
 only:
 - master

build_image:
script:
- docker build -t maros/face-recognition
- docker run -p maros/face-recognition

