image: node:8.11.1

pages:
 cache:
  paths:
  - node_modules/

 before_script:
 - yarn global add forever

 stage: deploy
 script:
 - yarn install
 - yarn build
 - rm -rf public
 - mv build public
 artifacts:
  paths:
  - public
 only:
 - master
